// <auto-generated />
using System;
using CoachTraining.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoachTraining.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260907051100_AthleteLookupIndexes")]
    partial class AthleteLookupIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoachTraining.Api.Models.Athlete", b =>
                {
                    b.Property<int>("AthleteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AthleteId"));

                    b.Property<string>("AthleteCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("AthleteLevel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("JoinDate")
                        .HasColumnType("date");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ParentName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ParentPhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AthleteId");

                    b.HasIndex("AthleteCode")
                        .IsUnique();

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttendanceId"));

                    b.Property<TimeOnly?>("ArrivalTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("AthleteCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer");

                    b.Property<string>("AthleteNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TrainingSessionId")
                        .HasColumnType("integer");

                    b.HasKey("AttendanceId");

                    b.HasIndex("AthleteId");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("TrainingSessionId", "AthleteId")
                        .IsUnique();

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ActionByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("text");

                    b.HasKey("AuditLogId");

                    b.HasIndex("ActionByUserId");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.Coach", b =>
                {
                    b.Property<int>("CoachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CoachId"));

                    b.Property<string>("CoachCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CoachType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("CoachId");

                    b.HasIndex("CoachCode")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.CoachSubstitutionHistory", b =>
                {
                    b.Property<int>("CoachSubstitutionHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CoachSubstitutionHistoryId"));

                    b.Property<int>("ActionByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OriginalCoachId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubstituteCoachId")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingSessionId")
                        .HasColumnType("integer");

                    b.HasKey("CoachSubstitutionHistoryId");

                    b.HasIndex("ActionByUserId");

                    b.HasIndex("OriginalCoachId");

                    b.HasIndex("SubstituteCoachId");

                    b.HasIndex("TrainingSessionId");

                    b.ToTable("CoachSubstitutionHistories");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.ConflictOverrideHistory", b =>
                {
                    b.Property<int>("ConflictOverrideHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConflictOverrideHistoryId"));

                    b.Property<int>("ActionByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConflictType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RoutineScheduleId")
                        .HasColumnType("integer");

                    b.Property<int?>("TrainingSessionId")
                        .HasColumnType("integer");

                    b.HasKey("ConflictOverrideHistoryId");

                    b.HasIndex("ActionByUserId");

                    b.HasIndex("RoutineScheduleId");

                    b.HasIndex("TrainingSessionId");

                    b.ToTable("ConflictOverrideHistories");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.PrivateSessionAthlete", b =>
                {
                    b.Property<int>("PrivateSessionAthleteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PrivateSessionAthleteId"));

                    b.Property<string>("AthleteCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer");

                    b.Property<string>("AthleteNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TrainingSessionId")
                        .HasColumnType("integer");

                    b.HasKey("PrivateSessionAthleteId");

                    b.HasIndex("AthleteId");

                    b.HasIndex("TrainingSessionId", "AthleteId")
                        .IsUnique();

                    b.ToTable("PrivateSessionAthletes");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.RoutineSchedule", b =>
                {
                    b.Property<int>("RoutineScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoutineScheduleId"));

                    b.Property<int>("CoachId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EffectiveEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EffectiveStartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RecurrencePattern")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoutineScheduleId");

                    b.HasIndex("CoachId", "DayOfWeek", "IsActive");

                    b.ToTable("RoutineSchedules");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.TrainingApprovalHistory", b =>
                {
                    b.Property<int>("TrainingApprovalHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrainingApprovalHistoryId"));

                    b.Property<int>("ActionByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("TrainingSessionId")
                        .HasColumnType("integer");

                    b.HasKey("TrainingApprovalHistoryId");

                    b.HasIndex("ActionByUserId");

                    b.HasIndex("TrainingSessionId");

                    b.ToTable("TrainingApprovalHistories");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.TrainingLog", b =>
                {
                    b.Property<int>("TrainingLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrainingLogId"));

                    b.Property<string>("AthleteNotes")
                        .HasColumnType("text");

                    b.Property<string>("CoachNotes")
                        .HasColumnType("text");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExerciseDrill")
                        .HasColumnType("text");

                    b.Property<string>("Focus")
                        .HasColumnType("text");

                    b.Property<string>("GeneralRemarks")
                        .HasColumnType("text");

                    b.Property<string>("Intensity")
                        .HasColumnType("text");

                    b.Property<string>("Objective")
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.Property<int>("TrainingSessionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TrainingLogId");

                    b.HasIndex("TrainingSessionId")
                        .IsUnique();

                    b.ToTable("TrainingLogs");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.TrainingSession", b =>
                {
                    b.Property<int>("TrainingSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrainingSessionId"));

                    b.Property<string>("ActualCoachCodeSnapshot")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("ActualCoachId")
                        .HasColumnType("integer");

                    b.Property<string>("ActualCoachNameSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ActualEndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualStartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedCoachCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("AssignedCoachId")
                        .HasColumnType("integer");

                    b.Property<string>("AssignedCoachNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<string>("ConflictOverrideReason")
                        .HasColumnType("text");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsConflictOverridden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("OriginalSessionId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int?>("RoutineScheduleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledEndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScheduledStartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TrainingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TrainingSessionId");

                    b.HasIndex("OriginalSessionId");

                    b.HasIndex("RoutineScheduleId");

                    b.HasIndex("SessionDate");

                    b.HasIndex("Status");

                    b.HasIndex("TrainingType");

                    b.HasIndex("ActualCoachId", "SessionDate");

                    b.HasIndex("AssignedCoachId", "SessionDate");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserRoleId"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.Attendance", b =>
                {
                    b.HasOne("CoachTraining.Api.Models.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoachTraining.Api.Models.User", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoachTraining.Api.Models.TrainingSession", "TrainingSession")
                        .WithMany("Attendances")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("RecordedByUser");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.AuditLog", b =>
                {
                    b.HasOne("CoachTraining.Api.Models.User", "ActionByUser")
                        .WithMany()
                        .HasForeignKey("ActionByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActionByUser");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.Coach", b =>
                {
                    b.HasOne("CoachTraining.Api.Models.User", "User")
                        .WithOne("Coach")
                        .HasForeignKey("CoachTraining.Api.Models.Coach", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.CoachSubstitutionHistory", b =>
                {
                    b.HasOne("CoachTraining.Api.Models.User", "ActionByUser")
                        .WithMany()
                        .HasForeignKey("ActionByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoachTraining.Api.Models.Coach", "OriginalCoach")
                        .WithMany()
                        .HasForeignKey("OriginalCoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoachTraining.Api.Models.Coach", "SubstituteCoach")
                        .WithMany()
                        .HasForeignKey("SubstituteCoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoachTraining.Api.Models.TrainingSession", "TrainingSession")
                        .WithMany()
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActionByUser");

                    b.Navigation("OriginalCoach");

                    b.Navigation("SubstituteCoach");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.ConflictOverrideHistory", b =>
                {
                    b.HasOne("CoachTraining.Api.Models.User", "ActionByUser")
                        .WithMany()
                        .HasForeignKey("ActionByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoachTraining.Api.Models.RoutineSchedule", "RoutineSchedule")
                        .WithMany()
                        .HasForeignKey("RoutineScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CoachTraining.Api.Models.TrainingSession", "TrainingSession")
                        .WithMany()
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActionByUser");

                    b.Navigation("RoutineSchedule");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.PrivateSessionAthlete", b =>
                {
                    b.HasOne("CoachTraining.Api.Models.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoachTraining.Api.Models.TrainingSession", "TrainingSession")
                        .WithMany("PrivateAthletes")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.RoutineSchedule", b =>
                {
                    b.HasOne("CoachTraining.Api.Models.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.TrainingApprovalHistory", b =>
                {
                    b.HasOne("CoachTraining.Api.Models.User", "ActionByUser")
                        .WithMany()
                        .HasForeignKey("ActionByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoachTraining.Api.Models.TrainingSession", "TrainingSession")
                        .WithMany()
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActionByUser");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.TrainingLog", b =>
                {
                    b.HasOne("CoachTraining.Api.Models.TrainingSession", "TrainingSession")
                        .WithOne("TrainingLog")
                        .HasForeignKey("CoachTraining.Api.Models.TrainingLog", "TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.TrainingSession", b =>
                {
                    b.HasOne("CoachTraining.Api.Models.Coach", "ActualCoach")
                        .WithMany()
                        .HasForeignKey("ActualCoachId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CoachTraining.Api.Models.Coach", "AssignedCoach")
                        .WithMany()
                        .HasForeignKey("AssignedCoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoachTraining.Api.Models.TrainingSession", "OriginalSession")
                        .WithMany("ReplacementSessions")
                        .HasForeignKey("OriginalSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CoachTraining.Api.Models.RoutineSchedule", "RoutineSchedule")
                        .WithMany()
                        .HasForeignKey("RoutineScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActualCoach");

                    b.Navigation("AssignedCoach");

                    b.Navigation("OriginalSession");

                    b.Navigation("RoutineSchedule");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.UserRole", b =>
                {
                    b.HasOne("CoachTraining.Api.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoachTraining.Api.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.TrainingSession", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("PrivateAthletes");

                    b.Navigation("ReplacementSessions");

                    b.Navigation("TrainingLog");
                });

            modelBuilder.Entity("CoachTraining.Api.Models.User", b =>
                {
                    b.Navigation("Coach");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
